image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind
  
stages:
  - build

build-job:
  stage: build
  image: docker:dind 
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t broc1603/lor-module --build-arg mongodb_connection_string=$MONGODB_CONNECTION_STRING .
    - docker push broc1603/lor-module
  rules:
     - if: '$CI_COMMIT_BRANCH == "main"'
